### ISSUE TITLE
haveing issues with "git push heroku master"

### ISSUE THREAD

**Issue by Gmunker** [citizenparker/holonet-relay#1]
c:\Users\Public\Documents\HOLONE~1>git push heroku master
Counting objects: 82, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (67/67), done.
Writing objects: 100% (82/82), 150.49 KiB | 0 bytes/s, done.
Total 82 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> elixir app detected
remote: -----> Checking Erlang and Elixir versions
remote:        Will use the following versions:
remote:        \* Erlang 17.3
remote:        \* Elixir 1.0.2
remote:        Will export the following config vars:
remote:        \* Config vars DATABASE_URL
remote:        Downloading Erlang package
remote: -----> Fetching Erlang 17.3
remote: -----> Installing Erlang 17.3
remote:
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Exiting with failure status due to previous errors
remote: /tmp/buildpack_dd612a7ea8bf2579bbfe77b84338e210/lib/erlang_funcs.sh: lin
e 39: /app/tmp/cache/erlang/Install: No such file or directory
remote: -----> Downloading Elixir
remote: -----> Installing Elixir v1.0.2
remote: -----> Installing Hex
remote: exec: 100: erl: not found
remote: -----> Installing rebar
remote: exec: 100: erl: not found
remote: -----> Fetching app dependencies with mix
remote: exec: 100: erl: not found
remote:
remote:  !     Push rejected, failed to compile elixir app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to vitalityholonet.
remote:
To https://git.heroku.com/vitalityholonet.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/vitalityholonet.git'

**Comment by Gmunker** [comment]
I think it's because it's trying to compile elixir v1.0.2 and i have Elixir 1.0.3-dev.

**Comment by sparkertime** [comment]
Hi! I'm going to try pushing this to a new Heroku remote and see what I find. I'll keep you posted.

SP

**Comment by sparkertime** [comment]
Heya @Gmunker - looks like the instructions in the README were no longer valid. In particular, the line that included `BUILDPACK_URL` pointed to the wrong location.

Sorry about that - I hadn't used this to deploy a new Heroku application in awhile.
